import "@/styles/globals.css";

import { type Metadata } from "next";
import { Lexend, Funnel_Sans, Geist } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/global/header";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(geist.variable, "h-full")}>
      <body className="flex min-h-full flex-col">
        <NuqsAdapter>
          <TRPCReactProvider>
            <Header />
            <div className="flex flex-1 flex-col">{children}</div>
          </TRPCReactProvider>
          <Toaster richColors position="top-center" />
        </NuqsAdapter>
      </body>
    </html>
  );
}
