import "@/styles/globals.css";

import { type Metadata } from "next";
import { Lexend, Funnel_Sans } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/global/header";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--display-family",
});

const funnel_sans = Funnel_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--text-family",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        lexend.variable,
        funnel_sans.variable,
        "bg-background h-full",
      )}
    >
      <body className="flex min-h-full flex-col">
        <TRPCReactProvider>
          <Header />
          <div className="flex flex-1 flex-col">{children}</div>
        </TRPCReactProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
